### ISSUE TITLE
Design a poster for the event.

### ISSUE THREAD

**Issue by DineshMv** [DineshMv/l10n-Telugu-meetup#1]
A poster is required to publicize in all l10n channels of swecha and mozilla. 

Deadline: 7th, June

**Comment by ranjithrajvasam** [comment]
I opened a issue at Mozilla Open Design repo
https://github.com/mozilla/OpenDesign/issues/134

**Comment by DineshMv** [comment]
Poster has been made by our contributor- nithin.
@ranjithrajvasam & @TheSahithi We can proceed with sharing with our community. 
Also share the registration page as well.
