### ISSUE TITLE
Event Space confirmation from Swecha

### ISSUE THREAD

**Issue by DineshMv** [DineshMv/l10n-Telugu-meetup#3]
Hi @ranjithrajvasam  /@thesahithi, 

Please confirm the details regarding the venue and stationary required for the event.

PS: You can close this issue after confirmation.

**Comment by ranjithrajvasam** [comment]
Venue is confirmed.
- Ranjith Raj,EC Member-Swecha.

**Comment by DineshMv** [comment]
Thanks for the update!
