### ISSUE TITLE
Evangelise about Firefox Focus for Android/iOS

### ISSUE THREAD

**Issue by DineshMv** [DineshMv/l10n-Telugu-meetup#4]
A small talk/demo about Firefox Focus.
Speakers Required: <i> Open </i> 

@TheSahithi Share this info with our community people and update here if anyone is interested.

**Comment by ranjithrajvasam** [comment]
Any documentation on 'Why focus is better than private browsing'?

**Comment by DineshMv** [comment]
Further actions related to this will be discussed in #9
