### ISSUE TITLE
New Contributors hands-on progress

### ISSUE THREAD

**Issue by DineshMv** [DineshMv/l10n-Telugu-meetup#5]
<i> Please fill the details accordingly. Based on contributions, Newbies will be invited to the event.  </i>

Name: 
Mail id:
Project Contributed to:
No. of strings translated: 
Typing Tool/Software used:
Feedback/suggestion:

**Comment by sairamraavi** [comment]
Name: sairam raavi
Mail id:sairam@riseup.net
Project Contributed to: Thimble
No. of strings translated: 24
Typing Tool/Software used: http://telugu.indiatyping.com/
Feedback/suggestion: better to add some guide lines before starting the convertions in the pantton website before every project.

**Comment by kotibannu541** [comment]
Name:T koteswararao
Mail id:turakakoteswararao9@gmail.com
Project Contributed to:Thimble
No. of strings translated:8
Typing Tool/Software used: Lekhini
Feedback/suggestion:

**Comment by sowjanya9515** [comment]
Name:lakshmi sowjanya kokkonda
Mail id:sowjanya.kokkonda@gmail.com
Project Contributed to:Thimble
No. of strings translated:3
Typing Tool/Software used: Lekhini
Feedback/suggestion:

**Comment by chittimoduspradeep** [comment]
Name:spradeep
Mail id:chittimoduspradeep@gmail.com
Project Contributed to:TesT polit:notes
No. of strings translated:8
Typing Tool/Software used: Lekhini
Feedback/suggestion:

**Comment by praneethreddym007** [comment]
Name:m.praneeth reddy
Mail id:praneethreddym007@gmail.com
Project Contributed to:TesT polit:notes
No. of strings translated:18
Typing Tool/Software used: Lekhini
Feedback/suggestion:

**Comment by banalahasini** [comment]
Name:banala hasini
Mail id:bhhasini1998@gmail.com
Project Contributed to:Test pilot Website
No. of strings translated:4
Typing Tool/Software used:Lekhini
Feedback/suggestion:

**Comment by banalahasini** [comment]
Name:banala hasini
Mail id:bhhasini1998@gmail.com
Project Contributed to:Test pilot Website
No. of strings translated:21
Typing Tool/Software used:Lekhini
Feedback/suggestion:

**Comment by chittimoduspradeep** [comment]
Name:spradeep
Mail id:chittimoduspradeep@gmail.com
Project Contributed to:MDN
No. of strings translated:46
Typing Tool/Software used:Lekhini
Feedback/suggestion:

**Comment by DineshMv** [comment]
Thanks every one for your interest. We will review your work and follow up with next steps. :)

**Comment by DineshMv** [comment]
@TheSahithi Please ask people who contributed recently to update here.

**Comment by DineshMv** [comment]
Applications has been reviewed and invitations has been sent.
