### ISSUE TITLE
Onboarding of reviewers

### ISSUE THREAD

**Issue by DineshMv** [DineshMv/l10n-Telugu-meetup#7]
By the end of this event, 2-3 new reviewers will be on boarded.

**Criteria:**
* Active since past months
* String approval/rejection ratio >= 90%
* Strings translated >1200
* Must be strongly committed for the next 6 months(atleast)
* Must be ready to take ownership of pending projects

**Comment by TheSahithi** [comment]
@TheSahithi was onboarded as a reviewer.
