### ISSUE TITLE
No. of Talks & Resource person assignment

### ISSUE THREAD

**Issue by DineshMv** [DineshMv/l10n-Telugu-meetup#9]
List out number of talks to be presented as per the agenda.

**| Topic                                 | Oraganization | Resource Person |**

**Comment by TheSahithi** [comment]
Finalised Talks : 
| అనువాద సమస్యలు , సవాళ్ళు | Mozilla | Veeven |
| Migrating documentation to wiki projects/wiki markup| Wikipedia| Pavan Santhosh |
| Intro to FOSS & Significance of Localization | Swecha | Sunil Mohan & Ranjith Raj Vasam |
| Freedom Box and oflfline Wikipedia | Swecha | Siddhartha Malempati |
| Mozilla L10n & Pontoon | Mozilla | Dinesh & Jayesh |
| Firefox Telugu | Swecha | Sahithi|
| Wikipedia Telugu | Wikipedia | Pranay Raj |

**Comment by TheSahithi** [comment]
| Topic | Oraganization | Resource Person |

**Comment by TheSahithi** [comment]
Topic | Oraganization | Resource Person 
------ |----------------- | -------------------
 Topic | Oraganization | Resource Person
